[package]
name = "neothesia"
version = "0.1.0"
authors = ["Poly <bartek.marynczak@op.pl>"]
edition = "2018"

[dependencies]
lib_midi = { path = "./src/lib_midi" }
midir = "0.5.0"
colored = "1.8"
nfd = "0.0.4"
glium = "0.25.0"
glium-glyph = "0.5.0"